version: 0.0
os: linux
files:
  - source: /
    destination: /code-deploy
permissions:
  - object: /root
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: scripts/reload-pm2.sh
      timeout: 300
      runas: ubuntu
