version: 0.0
os: linux
files:
  - source: /
    destination: /aws-codedeploy
permissions:
  - object: /root
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: scripts/reload-pm2.sh
      timeout: 300
      runas: ec2-user
